### ISSUE TITLE
How can I use it to draw svg images?

### ISSUE THREAD

**Issue by aocriup233** [Flundrahn/manim-fourier-project#1]

**Comment by Flundrahn** [comment]
I haven't tried it myself, but it should be something like this.

- checkout the latest commit
- instead of using the Tex symbol you want to create a [SVGMobject](https://docs.manim.community/en/stable/reference/manim.mobject.svg.svg_mobject.SVGMobject.html#manim.mobject.svg.svg_mobject.SVGMobject)
- looks like the constructor works by taking the path to a SVG file
- the method `get_path_from_symbol` works on any Mobject, it will extract the first path from your SVGMobject
- pass that path as argument to `get_fourier_vectors`

Note I only wrote my code to handle one path, so if you'd want to use multiple paths you would have to customize the code further. I hope this works for you!

**Comment by Flundrahn** [comment]
I have a vague memory of the original Theorem of Beethoven video or repo mentioning how to use with SVG:s, I'll close this issue as I won't implement myself, but let me know if you get it working!
